### PR TITLE
LSTM Autoencoder

### PR DESCRIPTION
**Pull request by Natalie-Caruana**

### CODE REVIEW

**Review by milesgranger — CHANGES_REQUESTED** [review]
Think it's pretty close, nice work.

Also _need_ tests. :100: 

- Define a pipeline in yaml and test loading and serializing it.
- Ensure the fit/predict operates as expected
- Explicitly test your generator functions (given X, or X and y) and expected outputs
- Test it will fail if asked to train on a smaller dataset than `lookback_window`
- Any other potential complications you can think of.

**Review by epa095 — COMMENTED** [review]
I LiKe It

**Review by milesgranger — COMMENTED** [review]
Sweet! :+1:  Will be cool to have this. Just minor comments, (sorry).. also noticed how much `black` obliterates formatting when a comment is on the same line as a statement, left a few comments on those instances.

**Review by epa095 — COMMENTED** [review]
Good work!

**Review by milesgranger — APPROVED** [review]

**Pull request merged**
